// ~~ Generated by projen. To modify, edit .projenrc.ts and run "npx projen".
import * as path from 'path';
import * as lambda from 'aws-cdk-lib/aws-lambda';
import { Construct } from 'constructs';

export interface PackageStatsAggregatorProps extends lambda.FunctionOptions {
}

export class PackageStatsAggregator extends lambda.Function {
  constructor(scope: Construct, id: string, props?: PackageStatsAggregatorProps) {
    super(scope, id, {
      description: 'backend/package-stats/package-stats-aggregator.lambda.ts',
      ...props,
      architecture: lambda.Architecture.ARM_64,
      runtime: lambda.Runtime.NODEJS_22_X,
      handler: 'index.handler',
      code: lambda.Code.fromAsset(path.join(__dirname, '/package-stats-aggregator.lambda.bundle')),
    });
  }
}