// ~~ Generated by projen. To modify, edit .projenrc.js and run "npx projen".
import * as path from 'path';
import * as lambda from '@aws-cdk/aws-lambda';
import { Construct } from '@aws-cdk/core';

export interface DiscoveryProps extends lambda.FunctionOptions {
}

export class Discovery extends lambda.Function {
  constructor(scope: Construct, id: string, props?: DiscoveryProps) {
    super(scope, id, {
      description: 'backend/discovery/discovery.lambda.ts',
      ...props,
      runtime: lambda.Runtime.NODEJS_14_X,
      handler: 'index.handler',
      code: lambda.Code.fromAsset(path.join(__dirname, '/discovery.bundle')),
    });
  }
}