// ~~ Generated by projen. To modify, edit .projenrc.ts and run "npx projen".
import * as path from 'path';
import * as lambda from 'aws-cdk-lib/aws-lambda';
import { Construct } from 'constructs';

export interface CatalogBuilderMockProps extends lambda.FunctionOptions {
}

export class CatalogBuilderMock extends lambda.Function {
  constructor(scope: Construct, id: string, props?: CatalogBuilderMockProps) {
    super(scope, id, {
      description: '__tests__/backend/deny-list/integ/catalog-builder-mock.lambda.ts',
      ...props,
      architecture: lambda.Architecture.ARM_64,
      runtime: lambda.Runtime.NODEJS_16_X,
      handler: 'index.handler',
      code: lambda.Code.fromAsset(path.join(__dirname, '/catalog-builder-mock.lambda.bundle')),
    });
  }
}