// ~~ Generated by projen. To modify, edit .projenrc.ts and run "yarn projen".
import * as path from 'path';
import * as lambda from 'aws-cdk-lib/aws-lambda';
import { Construct } from 'constructs';

export interface PackumentProcessorProps extends lambda.FunctionOptions {
}

export class PackumentProcessor extends lambda.Function {
  constructor(scope: Construct, id: string, props?: PackumentProcessorProps) {
    super(scope, id, {
      description: 'package-sources/npmjs/packument-processor.lambda.ts',
      ...props,
      architecture: lambda.Architecture.ARM_64,
      runtime: lambda.Runtime.NODEJS_22_X,
      handler: 'index.handler',
      code: lambda.Code.fromAsset(path.join(__dirname, '/packument-processor.lambda.bundle')),
    });
  }
}