// ~~ Generated by projen. To modify, edit .projenrc.ts and run "npx projen".
import * as path from 'path';
import * as lambda from 'aws-cdk-lib/aws-lambda';
import { Construct } from 'constructs';

export interface StageAndNotifyProps extends lambda.FunctionOptions {
}

export class StageAndNotify extends lambda.Function {
  constructor(scope: Construct, id: string, props?: StageAndNotifyProps) {
    super(scope, id, {
      description: 'package-sources/npmjs/stage-and-notify.lambda.ts',
      ...props,
      architecture: lambda.Architecture.ARM_64,
      runtime: lambda.Runtime.NODEJS_20_X,
      handler: 'index.handler',
      code: lambda.Code.fromAsset(path.join(__dirname, '/stage-and-notify.lambda.bundle')),
    });
  }
}