// ~~ Generated by projen. To modify, edit .projenrc.js and run "npx projen".
import * as path from 'path';
import * as lambda from '@aws-cdk/aws-lambda';
import { Construct } from '@aws-cdk/core';

export interface GetMessagesFromWorkerQueueProps extends lambda.FunctionOptions {
}

export class GetMessagesFromWorkerQueue extends lambda.Function {
  constructor(scope: Construct, id: string, props?: GetMessagesFromWorkerQueueProps) {
    super(scope, id, {
      description: 'backend/release-notes/get-messages-from-worker-queue.lambda.ts',
      ...props,
      runtime: lambda.Runtime.NODEJS_14_X,
      handler: 'index.handler',
      code: lambda.Code.fromAsset(path.join(__dirname, '/get-messages-from-worker-queue.lambda.bundle')),
    });
  }
}