// ~~ Generated by projen. To modify, edit .projenrc.ts and run "npx projen".
import * as path from 'path';
import * as lambda from 'aws-cdk-lib/aws-lambda';
import { Construct } from 'constructs';

export interface CatalogBuilderProps extends lambda.FunctionOptions {
}

export class CatalogBuilder extends lambda.Function {
  constructor(scope: Construct, id: string, props?: CatalogBuilderProps) {
    super(scope, id, {
      description: 'backend/catalog-builder/catalog-builder.lambda.ts',
      ...props,
      architecture: lambda.Architecture.ARM_64,
      runtime: lambda.Runtime.NODEJS_16_X,
      handler: 'index.handler',
      code: lambda.Code.fromAsset(path.join(__dirname, '/catalog-builder.lambda.bundle')),
    });
  }
}