name: Feature request
description: Request a new feature
title: "short issue description"
labels: [feature-request, needs-triage]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Short description of the feature you are proposing.
    validations:
      required: false

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: |
        Why do you need this feature?
    validations:
      required: false

  - type: textarea
    id: other
    attributes:
      label: Other information
      description: |
        e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. associated pull-request, stackoverflow, slack, etc
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        ---

        This is a :rocket: Feature Request
