name: Website bug report
description: Report a bug with the Construct Hub website.
title: "short issue description"
labels: [bug, needs-triage]
body:
  - type: input
    id: url
    attributes:
      label: What is the URL of the page with the issue?
    validations:
      required: false

  - type: textarea
    id: problem
    attributes:
      label: What did you do?
    validations:
      required: false

  - type: textarea
    id: expected
    attributes:
      label: What did you expect to happen?
    validations:
      required: false

  - type: textarea
    id: actual
    attributes:
      label: What actually happened?
    validations:
      required: false

  - type: input
    id: web-browser
    attributes:
      label: Web Browser
    validations:
      required: false

  - type: input
    id: operating-system
    attributes:
      label: OS
    validations:
      required: false

  - type: textarea
    id: other
    attributes:
      label: Other information
      description: |
        e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. associated pull-request, stackoverflow, slack, etc
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        ---

        This is :bug: Bug Report
