// ~~ Generated by projen. To modify, edit .projenrc.ts and run "npx projen".
import * as path from 'path';
import * as lambda from 'aws-cdk-lib/aws-lambda';
import { Construct } from 'constructs';

export interface ListObjectsProps extends lambda.FunctionOptions {
}

export class ListObjects extends lambda.Function {
  constructor(scope: Construct, id: string, props?: ListObjectsProps) {
    super(scope, id, {
      description: 'backend/ingestion/list-objects.lambda.ts',
      ...props,
      architecture: lambda.Architecture.ARM_64,
      runtime: lambda.Runtime.NODEJS_22_X,
      handler: 'index.handler',
      code: lambda.Code.fromAsset(path.join(__dirname, '/list-objects.lambda.bundle')),
    });
  }
}
