// ~~ Generated by projen. To modify, edit .projenrc.js and run "npx projen".
import * as path from 'path';
import * as lambda from 'aws-cdk-lib/aws-lambda';
import { Construct } from 'constructs';

export interface ReIngestProps extends lambda.FunctionOptions {
}

export class ReIngest extends lambda.Function {
  constructor(scope: Construct, id: string, props?: ReIngestProps) {
    super(scope, id, {
      description: 'backend/ingestion/re-ingest.lambda.ts',
      ...props,
      runtime: lambda.Runtime.NODEJS_16_X,
      handler: 'index.handler',
      code: lambda.Code.fromAsset(path.join(__dirname, '/re-ingest.lambda.bundle')),
    });
  }
}