// ~~ Generated by projen. To modify, edit .projenrc.ts and run "npx projen".
import * as path from 'path';
import * as lambda from 'aws-cdk-lib/aws-lambda';
import { Construct } from 'constructs';

export interface MonitorProps extends lambda.FunctionOptions {
}

export class Monitor extends lambda.Function {
  constructor(scope: Construct, id: string, props?: MonitorProps) {
    super(scope, id, {
      description: 'backend/ecs-task-monitor/monitor.lambda.ts',
      ...props,
      architecture: lambda.Architecture.ARM_64,
      runtime: lambda.Runtime.NODEJS_20_X,
      handler: 'index.handler',
      code: lambda.Code.fromAsset(path.join(__dirname, '/monitor.lambda.bundle')),
    });
  }
}