// ~~ Generated by projen. To modify, edit .projenrc.js and run "npx projen".
import * as path from 'path';
import * as lambda from '@aws-cdk/aws-lambda';
import { Construct } from '@aws-cdk/core';

export interface FileUploaderProps extends lambda.FunctionOptions {
}

export class FileUploader extends lambda.Function {
  constructor(scope: Construct, id: string, props?: FileUploaderProps) {
    super(scope, id, {
      description: 'webapp/live-config/file-uploader.lambda.ts',
      ...props,
      runtime: lambda.Runtime.NODEJS_14_X,
      handler: 'index.handler',
      code: lambda.Code.fromAsset(path.join(__dirname, '/file-uploader.bundle')),
    });
  }
}