// ~~ Generated by projen. To modify, edit .projenrc.ts and run "npx projen".
import * as path from 'path';
import * as lambda from 'aws-cdk-lib/aws-lambda';
import { Construct } from 'constructs';

export interface NeedsCatalogUpdateProps extends lambda.FunctionOptions {
}

export class NeedsCatalogUpdate extends lambda.Function {
  constructor(scope: Construct, id: string, props?: NeedsCatalogUpdateProps) {
    super(scope, id, {
      description: 'backend/orchestration/needs-catalog-update.lambda.ts',
      ...props,
      architecture: lambda.Architecture.ARM_64,
      runtime: lambda.Runtime.NODEJS_16_X,
      handler: 'index.handler',
      code: lambda.Code.fromAsset(path.join(__dirname, '/needs-catalog-update.lambda.bundle')),
    });
  }
}