// ~~ Generated by projen. To modify, edit .projenrc.ts and run "npx projen".
import * as path from 'path';
import * as lambda from 'aws-cdk-lib/aws-lambda';
import { Construct } from 'constructs';

export interface ReadUninstallableReportProps extends lambda.FunctionOptions {
}

export class ReadUninstallableReport extends lambda.Function {
  constructor(scope: Construct, id: string, props?: ReadUninstallableReportProps) {
    super(scope, id, {
      description: 'backend/orchestration/read-uninstallable-report.lambda.ts',
      ...props,
      architecture: lambda.Architecture.ARM_64,
      runtime: lambda.Runtime.NODEJS_22_X,
      handler: 'index.handler',
      code: lambda.Code.fromAsset(path.join(__dirname, '/read-uninstallable-report.lambda.bundle')),
    });
  }
}