// ~~ Generated by projen. To modify, edit .projenrc.ts and run "npx projen".
import * as path from 'path';
import * as lambda from 'aws-cdk-lib/aws-lambda';
import { Construct } from 'constructs';

export interface RedriveStateMachineProps extends lambda.FunctionOptions {
}

export class RedriveStateMachine extends lambda.Function {
  constructor(scope: Construct, id: string, props?: RedriveStateMachineProps) {
    super(scope, id, {
      description: 'backend/orchestration/redrive-state-machine.lambda.ts',
      ...props,
      runtime: lambda.Runtime.NODEJS_16_X,
      handler: 'index.handler',
      code: lambda.Code.fromAsset(path.join(__dirname, '/redrive-state-machine.lambda.bundle')),
    });
  }
}