// ~~ Generated by projen. To modify, edit .projenrc.js and run "npx projen".
import * as path from 'path';
import * as lambda from '@aws-cdk/aws-lambda';
import { Construct } from '@aws-cdk/core';

export interface HandlerProps extends lambda.FunctionOptions {
}

export class Handler extends lambda.Function {
  constructor(scope: Construct, id: string, props?: HandlerProps) {
    super(scope, id, {
      description: 'webapp/cache-invalidator/handler.lambda.ts',
      architecture: lambda.Architecture.ARM_64,
      ...props,
      runtime: lambda.Runtime.NODEJS_14_X,
      handler: 'index.handler',
      code: lambda.Code.fromAsset(path.join(__dirname, '/handler.bundle')),
    });
  }
}