/* eslint-disable */
// This file was generated by the construct-hub
import type { AppConfig } from "../types/config";

const config: AppConfig = {"hasAnalytics":false,"disableContent":{"faq":true}};

export default config;
