// ~~ Generated by projen. To modify, edit .projenrc.js and run "npx projen".
import * as path from 'path';
import * as lambda from 'aws-cdk-lib/aws-lambda';
import { Construct } from 'constructs';

export interface SqsDlqStatsWidgetFunctionProps extends lambda.FunctionOptions {
}

export class SqsDlqStatsWidgetFunction extends lambda.SingletonFunction {
  constructor(scope: Construct, id: string, props?: SqsDlqStatsWidgetFunctionProps) {
    super(scope, id, {
      description: 'overview-dashboard/sqs-dlq-stats-widget-function.lambda.ts',
      ...props,
      uuid: 'fc176846-044f-5e56-baf2-c71723501885',
      lambdaPurpose: 'SQSDLQStatsWidget-Handler',
      runtime: lambda.Runtime.NODEJS_16_X,
      handler: 'index.handler',
      code: lambda.Code.fromAsset(path.join(__dirname, '/sqs-dlq-stats-widget-function.lambda.bundle')),
    });
  }
}