// ~~ Generated by projen. To modify, edit .projenrc.js and run "npx projen".
import * as lambda from '@aws-cdk/aws-lambda';
import { Construct } from 'constructs';

export interface FooProps extends Omit<lambda.FunctionProps, 'code' | 'handler' | 'runtime'> {
}

export class Foo extends lambda.Function {
  constructor(scope: Construct, id: string, props: FooProps = {}) {
    super(scope, id, {
      runtime: lambda.Runtime.NODEJS_14_X,
      handler: 'index.handler',
      code: lambda.Code.fromAsset(__dirname + '/foo.bundle'),
      ...props,
    });
  }
}