// ~~ Generated by projen. To modify, edit .projenrc.js and run "npx projen".
import * as path from 'path';
import * as lambda from 'aws-cdk-lib/aws-lambda';
import { Construct } from 'constructs';

export interface PruneQueueHandlerProps extends lambda.FunctionOptions {
}

export class PruneQueueHandler extends lambda.Function {
  constructor(scope: Construct, id: string, props?: PruneQueueHandlerProps) {
    super(scope, id, {
      description: 'backend/deny-list/prune-queue-handler.lambda.ts',
      ...props,
      runtime: lambda.Runtime.NODEJS_14_X,
      handler: 'index.handler',
      code: lambda.Code.fromAsset(path.join(__dirname, '/prune-queue-handler.lambda.bundle')),
    });
  }
}