// ~~ Generated by projen. To modify, edit .projenrc.js and run "npx projen".
import * as path from 'path';
import * as lambda from '@aws-cdk/aws-lambda';
import { Construct } from '@aws-cdk/core';

export interface SqsDlqStatsWidgetFunctionProps extends lambda.FunctionOptions {
}

export class SqsDlqStatsWidgetFunction extends lambda.SingletonFunction {
  constructor(scope: Construct, id: string, props?: SqsDlqStatsWidgetFunctionProps) {
    super(scope, id, {
      description: 'on-call-dashboard/sqs-dlq-stats-widget-function.lambda.ts',
      ...props,
      uuid: '9380f4de-fd31-5b3e-a633-9b992a1a201e',
      lambdaPurpose: 'SQSDLQStatsWidget-Handler',
      runtime: lambda.Runtime.NODEJS_14_X,
      handler: 'index.handler',
      code: lambda.Code.fromAsset(path.join(__dirname, '/sqs-dlq-stats-widget-function.lambda.bundle')),
    });
  }
}